import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "@pigment-css/react/styles.css"
import "./globals.css"
import NavBar from "./NavBar"
import { styled } from "@pigment-css/react"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

const ContentWrapper = styled("div")({
	width: "70%",
	height: "calc(100vh - 70px)",
	border: "1px solid black",
	margin: "0 auto",
	backgroundColor: "#FFF",
	"@media (max-width: 1024px)": {
		width: "100%",
	},
})

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body
				className={inter.className}
				style={{
					backgroundColor: "#CBF3F0",
				}}
			>
				<NavBar />
				<ContentWrapper>{children}</ContentWrapper>
			</body>
		</html>
	)
}
