import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "@pigment-css/react/styles.css"
import "./globals.css"
/** ref: https://docs.fontawesome.com/web/use-with/react/use-with */
import { config } from "@fortawesome/fontawesome-svg-core"
import "@fortawesome/fontawesome-svg-core/styles.css"
import NavBar from "./NavBar"
config.autoAddCss = false

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<NavBar />
				{children}
			</body>
		</html>
	)
}
