name: Pull Request Action
on:
  create:

jobs:
  create-pull-request:
    if: startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: stagging

      - name: Read PR template
        id: pr_template
        run: |
          echo 'body<<EOF' >> $GITHUB_OUTPUT
          cat .github/pull_request_template.md >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: '${{ github.ref_name }}',
              owner,
              repo,
              head: '${{ github.ref_name }}',
              base: 'stagging',
              body: ${{ steps.pr_template.outputs.body }},
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['feature', 'automated pr']
            });
