name: Pull Request Action
on:
  create:

jobs:
  create-pull-request:
    if: startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: stagging

      - name: Read PR template
        id: pr_template
        run: |
          echo 'body<<EOF' >> $GITHUB_OUTPUT
          cat .github/pull_request_template.md >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Maki0419-git/miyu-website/pulls \
            -d '{"title":"${{ github.ref_name }}","body":"","head":"${{ github.ref_name }}","base":"stagging"}'
