name: Pull Request Action
on:
  create:

jobs:
  create-pull-request:
    if: startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: stagging

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Maki0419-git/miyu-website/pulls \
            -d '{"title":"${{ github.ref_name }}","body":"## Proposed Change\r\n\r\n\r\n\r\n## Solution\r\n\r\n\r\n\r\n## Related Info\r\n\uD83D\uDCC5 \u65E5\u671F : \r\n\r\n\uD83D\uDDD2\uFE0F clickup :\r\n\r\n\uD83E\uDDD1\u200D\uD83C\uDFA8 figma:\r\n\r\n\uD83D\uDC3E issue: \r\n\r\n\uD83D\uDCD3 others:\r\n\r\n## I am abided to...\uFF1A\r\n- [ ] \u5927\u5BB6\u6240\u8A02\u5B9A\u7684 [Git comment \u683C\u5F0F](https:\/\/app.clickup.com\/5719919\/docs\/5ehvf-1720)\r\n- [ ] \u6BCF\u500B commit \u4E0D\u8D85\u904E 200 \u884C\u8B8A\u52D5\r\n- [ ] \u6BCF\u500B  PR \u4E0D\u8D85\u904E 500 \u884C\u8B8A\u52D5\r\n","head":"${{ github.ref_name }}","base":"stagging"}'
