name: Release on Deployment

on:
  deployment_status:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/Maki0419-git/miyu-website/releases \
          -d '{"tag_name":"v${{ github.run_number }}","target_commitish":"main","name":"Release v${{ github.run_number }}","body":"Release triggered by successful deployment.","draft":false,"prerelease":false,"generate_release_notes":false}'
         